                             GLfloat     moveOutLine[]                 =  {0, 0.73, 2.52};
                             GLfloat     hideSet_POSITION[]       =  {2.34, -1.75, -3.58189};
                             GLfloat     lightAttenuation_4view    =       1.5;
                             GLfloat     rotateTemp1               =       7;
                             GLfloat     rotateTemp2               =       0;
 //--------------------------------------------------------------------------------------;
   look_LEFT_RIGHT = 0;
   look_UP_DOWN    = 23.5;
   eyePosition[0]  = 0;
   eyePosition[1]  = -0.9;
   eyePosition[2]  = -3.39159;
 //--------------------------------------------------------------------------------------;
   moveSet[0]  = 0;
   moveSet[1]  = 0;
   moveSet[2]  = 0;
 //--------------------------------------------------------------------------------------;
   shadows_TextureDisplacement_X = -0.51661;
   shadows_TextureDisplacement_Y = 0;
 //--------------------------------------------------------------------------------------;
